version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: hackathon-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hackathon
      MYSQL_USER: uttc
      MYSQL_PASSWORD: Uttc@hackathon2025!
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: